# Generated by Django 3.1.4 on 2021-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210127_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.BigIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.BigIntegerField(default=0.0),
        ),
    ]
