# Generated by Django 3.1.4 on 2021-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210628_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
